### ISSUE TITLE
Question - How can I update the model value outside of the zone?

### ISSUE THREAD

**Issue by bytelabsco** [angular-extensions/model#2]
This may be out of the scope of this library, but thought I'd ask.  I'm trying to use the html5 navigator api's to watch a user's position.  I would then like to update the Position model.

What i'm getting right now is the code runs, but the model's value doesn't actually update.  Here's an abbreviated version:

```
 private model: Model<Position>;

constructor(private modelFactory: ModelFactory<Position>){

    this.model = this.modelFactory.create(initialData);
    this.userPosition$ = this.model.data$;

    navigator.geolocation.watchPosition(this.updatePosition);
}

private updatePosition = (position: Position) => {
    this.model.set(position);
}
```

I have also tried forcing it to run in the zone:

```
 private model: Model<Position>;

constructor(private modelFactory: ModelFactory<Position>, private ngZone: NgZone){

    this.model = this.modelFactory.create(initialData);
    this.userPosition$ = this.model.data$;

    navigator.geolocation.watchPosition((position) => this.ngZone.run(() => {

        this.model.set(position);

    }));
}
```

I feel like I'm missing something obvious here.

**Comment by tomastrajan** [comment]
Well this should work because `model.set()` is just a plain function which pushes new value to the all components subscribed to `this.userPosition$`.

Can you please elaborate a bit more on what does
> the code runs, but the model's value doesn't actually update
mean?

```ts
private updatePosition = (position: Position) => {
    console.log('CALLED');
    this.model.set(position);
}
```

Would this log?

The thing is it really should not need zone or anything because it's pure observabe pushing new value.
Anyway what you can try, even though it shouldn't be necessary is to inject `cd: ChangdeDetectionRef`
and then call `this.cd.markForCheck()` (or something similar, don;t remember the API by heart)

Pls, let me know how you solve this. We can include it the docs ( feel free to submit PR so that we can help others facing similar problems )

**Comment by bytelabsco** [comment]
A quick follow-up after some more research.  It turns out that all of the properties of Position from geolocation are actually on the prototype and not on the Position object.  JSON.stringify only applies to properties of the object, and will not chase the hierarchy.  The workaround for me was to manually copy the properties over to a new object.  Thanks for the quick response.
