### ISSUE TITLE
Default Clone removes Date typing

### ISSUE THREAD

**Issue by JarekToro** [angular-extensions/model#9]
## Minimal reproduction of the bug with instructions:

```js
//DataType is {date: Date}

this.model.data$.subscribe(x => {
console.log(x[0].date) // this is a string
})

this.model.set([{date:new Date()}])
```

## Expected behavior:
Should retain its `Date` typing

## Other information:
This is because we do a 
```js
JSON.parse(JSON.stringify(obj))
```
to copy

Is there a reason 
```js
//For Object
Object.assign({},obj)
//For Array
[...objs]
```
wouldn't work
## I would be willing to submit a PR to fix this issue:

[x] Yes (Assistance is provided if you need help submitting a pull request)  
[ ] No

**Comment by tomastrajan** [comment]
@JarekToro hey! The reason is that if you had nested object the nested references would be preserved and hence mutable, in ur case you can pass in custom `clone` function ta handle dates in special way! 

In general is usualy better to handle dates as iso strings and let the ui do to the whatever nevessary!
Cheers!
